### PR TITLE
Use font-awesome for Board Rules navbar icon

### PR DESCRIPTION
**Pull request by VSEphpbb**
Replace 3.1 style icons with 3.2 font awesome icons for phpBB3.2:
screen shot 2015-09-20 at 11 33 18 pm

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Updated: Users can type in an alternate font icon by name. Also added a little feature so the icon's are previewed dynamically in the ACP when typing it in:
screen shot 2015-09-22 at 12 50 56 pm

screen shot 2015-09-22 at 12 51 57 pm

**Comment by rxu** [comment]
Looks good to me, thanks @VSEphpbb ;)

**Comment by VSEphpbb** [comment]
@rxu made a little change ^^

**Comment by rxu** [comment]
Looks fine anyway :)

**Comment by VSEphpbb** [comment]
This PR is done, but added the new travis/composer updates so tests will pass when merged.

**Pull request merged**
