### PR TITLE
Update the text reparser

### PR DESCRIPTION
**Pull request by VSEphpbb**
Depends on phpBB PR https://github.com/phpbb/phpbb/pull/4010/files

### CODE REVIEW

**Comment by Elsensee** [comment]
PR is merged. :)

**Comment by michaelcullum** [comment]
'Fix tests'.... heh

**Comment by VSEphpbb** [comment]
Now this depends on another phpBB problem: https://github.com/phpbb/phpbb/pull/4020

**Comment by Elsensee** [comment]
That PR is merged too, now. :D

**Comment by VSEphpbb** [comment]
And now we pass ;)

**Pull request merged**
